line-length = 100

[lint]
select = ["E", "F", "W"]
ignore = [
    "E201",
    "E202",
    "E221",
    "E222",
    "E231",
    "E251",
    "E261",
    "E271",
    "E272",
    "E302",
    "E402",
    "E741",
    "W391",
]
