#!/usr/bin/env python3
"""
End-to-end validation for GazeboBridge (Step F acceptance test).

Requires a running Gazebo instance with scenario_world loaded:
    ros2 launch ocelot sim_launch.py world:=scenario_world headless:=true

Run inside the sim container:
    python3 /ws/src/ocelot/sim/scenario_generator/validate_bridge.py

Exit 0 = all checks passed.  Exit 1 = one or more checks failed.
"""

import subprocess
import sys
import time

# Must be inside the container (gz.transport available) to be useful.
from sim.scenario_generator.gazebo_bridge import GazeboBridge, _GZ_AVAILABLE

WORLD = "scenario_world"

# Use the pirate face texture that ships with the model — always present.
FACE_TEXTURE = "/ws/src/ocelot/sim/models/face_billboard/materials/textures/pirate.png"

# Plain-white background (generated by generate_backgrounds.py).
BG_TEXTURE = "/ws/src/ocelot/sim/assets/backgrounds/plain_white.png"

PASS = "\033[32mPASS\033[0m"
FAIL = "\033[31mFAIL\033[0m"


def gz_model_list() -> list[str]:
    """Return model names currently in WORLD via `gz model --list`."""
    result = subprocess.run(
        ["gz", "model", "--list", "-w", WORLD],
        capture_output=True, text=True, timeout=10,
    )
    names = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if line and not line.startswith("Requesting"):
            names.append(line)
    return names


def check(label: str, condition: bool) -> bool:
    print(f"  {'[ OK ]' if condition else '[FAIL]'}  {label}")
    return condition


def main() -> int:
    if not _GZ_AVAILABLE:
        print("ERROR: gz-transport not available — run this inside the sim container.")
        return 1

    bridge = GazeboBridge(world=WORLD)
    failures = 0

    # ------------------------------------------------------------------
    print("\n── 1. Service probe ─────────────────────────────────────────")
    from gz.transport13 import Node
    node = Node()
    services = node.service_list()
    create_svc = f"/world/{WORLD}/create"
    ok = create_svc in services
    if not check(f"{create_svc!r} in service list", ok):
        failures += 1
        print(f"     Available services: {services}")
        print("     Is the sim running?  Aborting remaining checks.")
        return 1

    # ------------------------------------------------------------------
    print("\n── 2. spawn_face (face_0) ───────────────────────────────────")
    ok = bridge.spawn_face("face_0", (2.0, 0.0, 0.8), FACE_TEXTURE)
    if not check("spawn_face returned True", ok):
        failures += 1
    time.sleep(1.0)
    models = gz_model_list()
    if not check("face_0 in gz model --list", "face_0" in models):
        failures += 1
        print(f"     models: {models}")

    # ------------------------------------------------------------------
    print("\n── 3. set_pose (face_0) ─────────────────────────────────────")
    ok = bridge.set_pose("face_0", 2.0, 0.5, 1.0)
    if not check("set_pose returned True", ok):
        failures += 1
    # No automated position readback in headless mode; True return is the gate.

    # ------------------------------------------------------------------
    print("\n── 4. spawn_background ──────────────────────────────────────")
    ok = bridge.spawn_background(BG_TEXTURE)
    if not check("spawn_background returned True", ok):
        failures += 1
    time.sleep(1.0)
    models = gz_model_list()
    if not check("background_wall in gz model --list", "background_wall" in models):
        failures += 1
        print(f"     models: {models}")

    # ------------------------------------------------------------------
    print("\n── 5. spawn_key_light ───────────────────────────────────────")
    ok = bridge.spawn_key_light(azimuth_deg=45.0, elevation_deg=30.0, intensity=1.5)
    if not check("spawn_key_light returned True", ok):
        failures += 1
    # Lights don't appear in gz model --list; True return is the gate.

    # ------------------------------------------------------------------
    print("\n── 6. spawn_distractor (sphere + box) ───────────────────────")
    ok1 = bridge.spawn_distractor("distractor_0", (1.5, 0.4, 0.6), "sphere", (0.8, 0.3, 0.3))
    ok2 = bridge.spawn_distractor("distractor_1", (2.5, -0.5, 0.5), "box",    (0.3, 0.7, 0.4))
    if not check("distractor_0 (sphere) spawn True", ok1):
        failures += 1
    if not check("distractor_1 (box) spawn True", ok2):
        failures += 1
    time.sleep(1.0)
    models = gz_model_list()
    if not check("distractor_0 in gz model --list", "distractor_0" in models):
        failures += 1
    if not check("distractor_1 in gz model --list", "distractor_1" in models):
        failures += 1

    # ------------------------------------------------------------------
    print("\n── 7. despawn ───────────────────────────────────────────────")
    ok = bridge.despawn("face_0")
    if not check("despawn face_0 returned True", ok):
        failures += 1
    time.sleep(1.0)
    models = gz_model_list()
    if not check("face_0 NOT in gz model --list after despawn", "face_0" not in models):
        failures += 1
        print(f"     models still present: {models}")

    # ------------------------------------------------------------------
    print("\n── 8. teardown_episode (clears all episode entities) ─────────")
    bridge.teardown_episode()
    time.sleep(1.0)
    models = gz_model_list()
    episode_leftovers = [m for m in models if m not in ("ground_plane", "ocelot")]
    if not check("no episode entities remain after teardown", not episode_leftovers):
        failures += 1
        print(f"     leftovers: {episode_leftovers}")

    # ------------------------------------------------------------------
    print("\n── 9. teardown idempotency ───────────────────────────────────")
    try:
        bridge.teardown_episode()
        bridge.teardown_episode()
        check("double teardown does not raise", True)
    except Exception as exc:
        check(f"double teardown does not raise ({exc})", False)
        failures += 1

    # ------------------------------------------------------------------
    print()
    if failures == 0:
        print(f"{PASS}  All checks passed.")
        return 0
    else:
        print(f"{FAIL}  {failures} check(s) failed.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
